### ISSUE TITLE
How import contact using this library

### ISSUE THREAD

**Issue by ruturajmaniyar** [idk-tn/yii2-google-apiclient#3]
Hello Team,

I have little confuse here. I need import all contacts from gmail account But I have no idea how to do it.
Kindly help out how process this functionality using this library.

**Comment by machour** [comment]
Hi @ruturajmaniyar !

We have an example for GMail messages receiving: https://github.com/idk-tn/yii2-google-apiclient#sample-usage

You just need to adapt it to use the Google Contact API: https://developers.google.com/google-apps/contacts/v3/. I think the service name will be `Google_Service_Contact`.
