### ISSUE TITLE
Error refreshing the OAuth2 token 

### ISSUE THREAD

**Issue by freetibet000** [idk-tn/yii2-google-apiclient#4]
Hello.
I try to use your library but i have issues with token refreshing.
After generating JSON file by your console helper it works perfect some time.
But from 1-2 hours i am getting next error:

Google_Auth_Exception
Error refreshing the OAuth2 token, message: '{
"error": "invalid_request",
"error_description": "Missing required parameter: refresh_token"
}'

Sorry, i mixed up repository so i recreated my question here.

**Comment by machour** [comment]
Check this SO question: https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token

I remember seeing this and solving it using `access_type=offline`

**Comment by freetibet000** [comment]
Thank you, it helped me

**Comment by machour** [comment]
Was it a problem with this library, or a configuration issue? A pull request would be really appreciated for both cases :)
